<?php
/**
 * DOCUMENTACIÓN TÉCNICA EN ESPAÑOL
 * Archivo: scripts/check_required_files.php
 * Propósito: Verifica automáticamente que la funcionalidad «required files» esté presente y sea coherente antes o después del despliegue.
 * Mantenimiento: los comentarios describen la intención y las decisiones relevantes;
 * no sustituyen las validaciones automáticas ni deben contener claves o contraseñas.
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$version = trim((string)@file_get_contents($root . '/VERSION'));
$required = [
    'README.md',
    'Actualizaciones.md',
    'config/environment.example',
    'src/SedeAssociator.php',
    'src/AppSettings.php',
    'src/DirectoryImporter.php',
    'src/InitializationState.php',
    'src/ImportQuality.php',
    'src/Importer.php',
    'src/WarehouseImporter.php',
    'src/WarehouseSedeAssociator.php',
    'src/SerialIntegrity.php',
    'src/AdditionalEquipmentIntegrity.php',
    'src/MobileScanBridge.php',
    'src/OperationalExperience.php',
    'src/ReportsCenter.php',
    'src/SystemHealth.php',
    'src/SecretVault.php',
    'src/MicrosoftGraphClient.php',
    'src/NotificationTemplate.php',
    'src/NotificationQueue.php',
    'src/NotificationService.php',
    'src/GlpiControlledSync.php',
    'src/SiteQualityGate.php',
    'src/PlatePolicy.php',
    'src/OnboardingService.php',
    'src/SiviRuntimeBridge.php',
    'src/ContactPrefillPolicy.php',
    'src/bootstrap.php',
    'src/Database.php',
    'scripts/check_release_files.php',
    'scripts/check_documentation_policy_1_0_0_0.php',
    'scripts/check_production_release.php',
    'scripts/check_required_files.php',
    'scripts/check_system_stability.php',
    'scripts/check_microsoft_graph_notifications.php',
    'scripts/notification_worker.php',
    'scripts/process_notification_queue.php',
    'scripts/check_repository_integrity.sh',
    'scripts/backup_dokploy.sh',
    'scripts/restore_dokploy_backup.sh',
    'scripts/check_sede_association.php',
    'scripts/check_warehouse_sede_association.php',
    'scripts/check_serial_integrity.php',
    'scripts/check_additional_equipment_integrity.php',
    'scripts/check_additional_equipment_form.php',
    'scripts/check_production_baseline.php',
    'scripts/build/run.php',
    'scripts/build/checks.json',
    'scripts/lib/CheckRunner.php',
    'scripts/lib/ProcessRunner.php',
    'scripts/maintenance/cleanup.php',
    'scripts/check_script_architecture_1_0_0_9.php',
    'scripts/check_application_optimization_1_0_0_10.php',
    'src/MalwareScanner.php',
    'src/UploadSecurity.php',
    'docker/db/98-sivi-least-privilege.sh',
    'scripts/process_backup_requests.sh',
    'scripts/prepare_soc_secret_files.sh',
    'scripts/check_soc_hardening_1_0_0_0.php',
    'scripts/check_ux_final_1_0_0_0.php',
    '.github/workflows/sivi-soc-security.yml',
    '.github/workflows/sivi-dast.yml',
    'public/assets/report-print.css',
    'public/assets/admin-plate-policy.css',
    'public/assets/offline.css',
    '.gitignore',
    '.dockerignore',
    'config/environment.secure.example',
    'docker-compose.secure-fragment.yml',
    'scripts/run_production_build_checks.sh',
    'scripts/register_current_release.php',
    'scripts/check_import_warehouse_serials.php',
    'scripts/check_warehouse_transaction.php',
    'scripts/check_user_roles_additional_equipment.php',
    'scripts/check_additional_equipment_persistence.php',
    'scripts/check_additional_identity_fallback.php',
    'scripts/check_additional_identity_popup.php',
    'scripts/check_additional_identity_timeout.php',
    'scripts/ensure_performance_indexes.php',
    'scripts/check_performance_optimization.php',
    'scripts/check_contact_phone_validation.php',
    'scripts/check_container_names.php',
    'scripts/check_container_name_formats.php',
    'scripts/check_volume_parser_1_0_0_11.php',
    'scripts/check_clean_relaunch_1_0_0_0.php',
    'scripts/check_clean_database_schema.php',
    'scripts/check_mobile_scan_bridge.php',
    'scripts/check_mobile_camera_fallback.php',
    'scripts/check_mobile_scan_robust.php',
    'scripts/check_site_closure_consistency.php',
    'scripts/check_print_report_layout.php',
    'scripts/check_reports_center.php',
    'scripts/check_mobile_pwa_responsive.php',
    'scripts/check_optimization.php',
    'scripts/healthcheck.php',
    'scripts/check_import_runtime.php',
    'scripts/check_initialization_flow.php',
    'scripts/check_quality_flow.php',
    'scripts/check_campaign_operation.php',
    'scripts/check_campaign_contact_flow.php',
    'scripts/check_validation_auto_next.php',
    'scripts/check_registrador_flow.php',
    'scripts/check_formador_flow.php',
    'scripts/check_guided_experience.php',
    'scripts/check_glpi_integration.php',
    'scripts/check_site_quality_gate.php',
    'scripts/check_secure_closure.php',
    'scripts/check_guided_ux.php',
    'scripts/verify_dokploy_backup.sh',
    'scripts/pre_deploy_secure.sh',
    'scripts/post_deploy_check.sh',
    'docker-compose-db.yml',
    'config/environment.db-server.example',
    'scripts/check_split_topology_1_0_0_0.php',
    'scripts/check_runtime_parameterization_1_0_0_0.php',
    'docker/entrypoint.sh',
    'docker/db/Dockerfile',
    'docker/db/99-sivi-register-release.sh',
    'public/index.php',
    'public/assets/app.js',
    'public/assets/app.css',
    'public/assets/report-print.js',
    'public/assets/mobile-scanner.js',
    'public/assets/mobile-scanner.css',
    'public/manifest.webmanifest',
    'public/sw.js',
    'public/offline.html',
    'public/ready.php',
    'public/admin-plate-policy.php',
    'public/plate-policy-config.php',
    'public/onboarding-status.php',
    'public/assets/plate-ux.css',
    'public/assets/plate-entry.js',
    'public/assets/sivi-onboarding.css',
    'public/assets/sivi-onboarding.js',
    'database/schema.sql',
    'database/schema.mysql84.sql',
    'docker/db/mysql-entrypoint-wrapper.sh',
    'docker/apache-sivi-security-strong.conf',
    'docker/backup/Dockerfile',
    'docker/backup/entrypoint.sh',
];

$checks = [];
$missing = [];
foreach ($required as $relative) {
    $path = $root . '/' . $relative;
    $exists = is_file($path) && filesize($path) > 0;
    $checks[$relative] = $exists;
    if (!$exists) $missing[] = $relative;
}

$ok = $missing === [];
echo json_encode([
    'ok' => $ok,
    'version' => $version,
    'check' => 'required_runtime_files_' . $version,
    'checks' => $checks,
    'missing' => $missing,
], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL;
exit($ok ? 0 : 2);
